// <auto-generated />
namespace KodlaManisa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CreateTblAtolyeYonlendirilenOgrencilersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTblAtolyeYonlendirilenOgrencilersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202005022307088_CreateTblAtolyeYonlendirilenOgrencilersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
