//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KodlaManisaEntities : DbContext
    {
        public KodlaManisaEntities()
            : base("name=KodlaManisaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAtolyeFotograf> tblAtolyeFotografs { get; set; }
        public virtual DbSet<tblAtolyeGelenZiyaretci> tblAtolyeGelenZiyaretcis { get; set; }
        public virtual DbSet<tblAtolyeKurslar> tblAtolyeKurslars { get; set; }
        public virtual DbSet<tblAtolyeKursOgrencileri> tblAtolyeKursOgrencileris { get; set; }
        public virtual DbSet<tblAtolyeler> tblAtolyelers { get; set; }
        public virtual DbSet<tblAtolyeMalzemeler> tblAtolyeMalzemelers { get; set; }
        public virtual DbSet<tblAtolyeOduncVerme> tblAtolyeOduncVermes { get; set; }
        public virtual DbSet<tblAtolyeTuru> tblAtolyeTurus { get; set; }
        public virtual DbSet<tblAtolyeYapilanZiyaretler> tblAtolyeYapilanZiyaretlers { get; set; }
        public virtual DbSet<tblDersler> tblDerslers { get; set; }
        public virtual DbSet<tblIlceler> tblIlcelers { get; set; }
        public virtual DbSet<tblIlkokulSorular> tblIlkokulSorulars { get; set; }
        public virtual DbSet<tblLiseSorular> tblLiseSorulars { get; set; }
        public virtual DbSet<tblOgrenciler> tblOgrencilers { get; set; }
        public virtual DbSet<tblOgrenciOgrenimBilgileri> tblOgrenciOgrenimBilgileris { get; set; }
        public virtual DbSet<tblOgretmenDYKBilgileri> tblOgretmenDYKBilgileris { get; set; }
        public virtual DbSet<tblOgretmenGorevlendirmeTuru> tblOgretmenGorevlendirmeTurus { get; set; }
        public virtual DbSet<tblOgretmenGorevYaptigiOkullar> tblOgretmenGorevYaptigiOkullars { get; set; }
        public virtual DbSet<tblOgretmenler> tblOgretmenlers { get; set; }
        public virtual DbSet<tblOkullar> tblOkullars { get; set; }
        public virtual DbSet<tblOkulMalzemeler> tblOkulMalzemelers { get; set; }
        public virtual DbSet<tblOkulOncesiSorular> tblOkulOncesiSorulars { get; set; }
        public virtual DbSet<tblOkulProjeEkibi> tblOkulProjeEkibis { get; set; }
        public virtual DbSet<tblOkulSiniflar> tblOkulSiniflars { get; set; }
        public virtual DbSet<tblOkulTeknolojiTakimi> tblOkulTeknolojiTakimis { get; set; }
        public virtual DbSet<tblOkulTuru> tblOkulTurus { get; set; }
        public virtual DbSet<tblOrtaokulSorular> tblOrtaokulSorulars { get; set; }
    }
}
