//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KodlaManisaEntities : DbContext
    {
        public KodlaManisaEntities()
            : base("name=KodlaManisaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAtolyeFotograf> tblAtolyeFotograf { get; set; }
        public virtual DbSet<tblAtolyeGelenZiyaretci> tblAtolyeGelenZiyaretci { get; set; }
        public virtual DbSet<tblAtolyeKurslar> tblAtolyeKurslar { get; set; }
        public virtual DbSet<tblAtolyeKursOgrencileri> tblAtolyeKursOgrencileri { get; set; }
        public virtual DbSet<tblAtolyeler> tblAtolyeler { get; set; }
        public virtual DbSet<tblAtolyeMalzemeler> tblAtolyeMalzemeler { get; set; }
        public virtual DbSet<tblAtolyeOduncVerme> tblAtolyeOduncVerme { get; set; }
        public virtual DbSet<tblAtolyeTuru> tblAtolyeTuru { get; set; }
        public virtual DbSet<tblAtolyeYapilanZiyaretler> tblAtolyeYapilanZiyaretler { get; set; }
        public virtual DbSet<tblDersler> tblDersler { get; set; }
        public virtual DbSet<tblIlceler> tblIlceler { get; set; }
        public virtual DbSet<tblIlkokulSorular> tblIlkokulSorular { get; set; }
        public virtual DbSet<tblLiseSorular> tblLiseSorular { get; set; }
        public virtual DbSet<tblOgrenciler> tblOgrenciler { get; set; }
        public virtual DbSet<tblOgrenciOgrenimBilgileri> tblOgrenciOgrenimBilgileri { get; set; }
        public virtual DbSet<tblOgretmenDYKBilgileri> tblOgretmenDYKBilgileri { get; set; }
        public virtual DbSet<tblOgretmenGorevlendirmeTuru> tblOgretmenGorevlendirmeTuru { get; set; }
        public virtual DbSet<tblOgretmenGorevYaptigiOkullar> tblOgretmenGorevYaptigiOkullar { get; set; }
        public virtual DbSet<tblOgretmenler> tblOgretmenler { get; set; }
        public virtual DbSet<tblOkullar> tblOkullar { get; set; }
        public virtual DbSet<tblOkulMalzemeler> tblOkulMalzemeler { get; set; }
        public virtual DbSet<tblOkulOncesiSorular> tblOkulOncesiSorular { get; set; }
        public virtual DbSet<tblOkulProjeEkibi> tblOkulProjeEkibi { get; set; }
        public virtual DbSet<tblOkulSiniflar> tblOkulSiniflar { get; set; }
        public virtual DbSet<tblOkulTeknolojiTakimi> tblOkulTeknolojiTakimi { get; set; }
        public virtual DbSet<tblOkulTuru> tblOkulTuru { get; set; }
        public virtual DbSet<tblOrtaokulSorular> tblOrtaokulSorular { get; set; }
    }
}
