//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeYapilanZiyaretler
    {
        public int ZiyaretID { get; set; }
        public Nullable<int> AtolyeID { get; set; }
        public string ZiyaretciAdi { get; set; }
        public Nullable<int> OkulID { get; set; }
        public Nullable<int> SinifID { get; set; }
        public Nullable<System.DateTime> ZiyaretTarihi { get; set; }
    
        public virtual tblAtolyeler tblAtolyeler { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
        public virtual tblOkulSiniflar tblOkulSiniflar { get; set; }
    }
}
