//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeMalzemeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAtolyeMalzemeler()
        {
            this.tblAtolyeOduncVermes = new HashSet<tblAtolyeOduncVerme>();
        }
    
        public int MalzemeID { get; set; }
        public Nullable<int> AtolyeID { get; set; }
        public string MalzemeAdi { get; set; }
        public Nullable<byte> MalzemeAdeti { get; set; }
        public Nullable<bool> MalzemeDurumu { get; set; }
        public string MalzemeTeminSekli { get; set; }
        public Nullable<System.DateTime> TeminTarihi { get; set; }
    
        public virtual tblAtolyeler tblAtolyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeOduncVerme> tblAtolyeOduncVermes { get; set; }
    }
}
