//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeOduncVerme
    {
        public int OduncVermeID { get; set; }
        public Nullable<int> AtolyeID { get; set; }
        public Nullable<int> MalzemeID { get; set; }
        public Nullable<byte> MalzemeSayisi { get; set; }
        public Nullable<int> OkulID { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
    
        public virtual tblAtolyeler tblAtolyeler { get; set; }
        public virtual tblAtolyeMalzemeler tblAtolyeMalzemeler { get; set; }
        public virtual tblOgretmenler tblOgretmenler { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
    }
}
