//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeKurslar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAtolyeKurslar()
        {
            this.tblAtolyeKursOgrencileris = new HashSet<tblAtolyeKursOgrencileri>();
        }
    
        public int KurslarID { get; set; }
        public Nullable<int> AtolyeID { get; set; }
        public string KursYili { get; set; }
        public string KursDönemi { get; set; }
        public string KursTuru { get; set; }
        public string KursSeviyesi { get; set; }
        public string KursGrubu { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public string GrupGunu { get; set; }
        public Nullable<System.TimeSpan> GrupSaati { get; set; }
    
        public virtual tblAtolyeler tblAtolyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeKursOgrencileri> tblAtolyeKursOgrencileris { get; set; }
    }
}
