//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeKursOgrencileri
    {
        public int GrupID { get; set; }
        public Nullable<int> KursID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<byte> DevamDurumu { get; set; }
        public Nullable<byte> OgrenciNot { get; set; }
        public string OgretmenGorusu { get; set; }
    
        public virtual tblAtolyeKurslar tblAtolyeKurslar { get; set; }
        public virtual tblOgrenciler tblOgrenciler { get; set; }
    }
}
