//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtolyeFotograf
    {
        public int FotografID { get; set; }
        public Nullable<int> AtolyeID { get; set; }
        public string FotografLink { get; set; }
    
        public virtual tblAtolyeler tblAtolyeler { get; set; }
    }
}
