//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDersler()
        {
            this.tblOgrenciOgrenimBilgileri = new HashSet<tblOgrenciOgrenimBilgileri>();
        }
    
        public int DersID { get; set; }
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public string DersYili { get; set; }
        public string DersDonemi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciOgrenimBilgileri> tblOgrenciOgrenimBilgileri { get; set; }
    }
}
