//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIlceler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIlceler()
        {
            this.tblAtolyeler = new HashSet<tblAtolyeler>();
            this.tblOgrenciler = new HashSet<tblOgrenciler>();
            this.tblOgretmenler = new HashSet<tblOgretmenler>();
            this.tblOkullar = new HashSet<tblOkullar>();
        }
    
        public int IlceID { get; set; }
        public string IlceAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeler> tblAtolyeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciler> tblOgrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenler> tblOgretmenler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkullar> tblOkullar { get; set; }
    }
}
