//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkullar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOkullar()
        {
            this.tblAtolyeGelenZiyaretcis = new HashSet<tblAtolyeGelenZiyaretci>();
            this.tblAtolyeOduncVermes = new HashSet<tblAtolyeOduncVerme>();
            this.tblAtolyeYapilanZiyaretlers = new HashSet<tblAtolyeYapilanZiyaretler>();
            this.tblIlkokulSorulars = new HashSet<tblIlkokulSorular>();
            this.tblLiseSorulars = new HashSet<tblLiseSorular>();
            this.tblOgrencilers = new HashSet<tblOgrenciler>();
            this.tblOgretmenDYKBilgileris = new HashSet<tblOgretmenDYKBilgileri>();
            this.tblOgretmenlers = new HashSet<tblOgretmenler>();
            this.tblOkulMalzemelers = new HashSet<tblOkulMalzemeler>();
            this.tblOkulOncesiSorulars = new HashSet<tblOkulOncesiSorular>();
            this.tblOkulProjeEkibis = new HashSet<tblOkulProjeEkibi>();
            this.tblOkulTeknolojiTakimis = new HashSet<tblOkulTeknolojiTakimi>();
            this.tblOrtaokulSorulars = new HashSet<tblOrtaokulSorular>();
        }
    
        public int OkulID { get; set; }
        public Nullable<int> OkulKodu { get; set; }
        public string OkulAdi { get; set; }
        public Nullable<int> OkulIlceAdi { get; set; }
        public Nullable<byte> OkulTuru { get; set; }
        public string OkulMuduru { get; set; }
        public Nullable<short> BTOgretmenSayisi { get; set; }
        public string OkulAdres { get; set; }
        public string OkulEposta { get; set; }
        public string OkulTel { get; set; }
        public string OkulFax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeGelenZiyaretci> tblAtolyeGelenZiyaretcis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeOduncVerme> tblAtolyeOduncVermes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeYapilanZiyaretler> tblAtolyeYapilanZiyaretlers { get; set; }
        public virtual tblIlceler tblIlceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIlkokulSorular> tblIlkokulSorulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLiseSorular> tblLiseSorulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciler> tblOgrencilers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenDYKBilgileri> tblOgretmenDYKBilgileris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenler> tblOgretmenlers { get; set; }
        public virtual tblOkulTuru tblOkulTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulMalzemeler> tblOkulMalzemelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulOncesiSorular> tblOkulOncesiSorulars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulProjeEkibi> tblOkulProjeEkibis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulTeknolojiTakimi> tblOkulTeknolojiTakimis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrtaokulSorular> tblOrtaokulSorulars { get; set; }
    }
}
