//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        public int OgrenciID { get; set; }
        public string OgrenciNo { get; set; }
        public string OgrenciTC { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> OkulID { get; set; }
        public Nullable<int> SinifID { get; set; }
        public string OgenciTelefon { get; set; }
        public string OgrenciEposta { get; set; }
        public string OgrenciVeli { get; set; }
        public string OgrenciVeliTelefon { get; set; }
        public string OgrenciVeliEposta { get; set; }
        public Nullable<int> OgrenciOgretmenID { get; set; }
        public string OkulOgretmeniGorus { get; set; }
        public string AtolyeOgetmeniGorus { get; set; }
        public Nullable<bool> OgrenciDurumu { get; set; }
    
        public virtual tblIlceler tblIlceler { get; set; }
        public virtual tblOgretmenler tblOgretmenler { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
        public virtual tblOkulSiniflar tblOkulSiniflar { get; set; }
        public virtual tblOgrenciOgrenimBilgileri tblOgrenciOgrenimBilgileri { get; set; }
    }
}
