//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgretmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOgretmenler()
        {
            this.tblAtolyeOduncVerme = new HashSet<tblAtolyeOduncVerme>();
            this.tblOgrenciler = new HashSet<tblOgrenciler>();
            this.tblOgretmenDYKBilgileri = new HashSet<tblOgretmenDYKBilgileri>();
            this.tblOgretmenGorevYaptigiOkullar = new HashSet<tblOgretmenGorevYaptigiOkullar>();
            this.tblOkulTeknolojiTakimi = new HashSet<tblOkulTeknolojiTakimi>();
        }
    
        public int OgretmenID { get; set; }
        public string OgretmenTC { get; set; }
        public string OgretmenAdi { get; set; }
        public string OgretmenSoyadi { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> OkulID { get; set; }
        public string OgretmenBrans { get; set; }
        public string OgretmenMezuniyet { get; set; }
        public Nullable<int> GorevlendirmeID { get; set; }
        public string OgretmenAdres { get; set; }
        public string OgretmenEposta { get; set; }
        public string OgretmenTel { get; set; }
        public Nullable<bool> OgretmenDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeOduncVerme> tblAtolyeOduncVerme { get; set; }
        public virtual tblIlceler tblIlceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciler> tblOgrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenDYKBilgileri> tblOgretmenDYKBilgileri { get; set; }
        public virtual tblOgretmenGorevlendirmeTuru tblOgretmenGorevlendirmeTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenGorevYaptigiOkullar> tblOgretmenGorevYaptigiOkullar { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulTeknolojiTakimi> tblOkulTeknolojiTakimi { get; set; }
    }
}
