//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkulMalzemeler
    {
        public int MalzemeID { get; set; }
        public Nullable<int> OkulID { get; set; }
        public string MalzemeAdi { get; set; }
        public Nullable<int> MalzemeAdedi { get; set; }
        public Nullable<byte> MalzemeDurumu { get; set; }
        public string MalzemeTeminSekli { get; set; }
        public Nullable<System.DateTime> TeminTarihi { get; set; }
    
        public virtual tblOkullar tblOkullar { get; set; }
    }
}
