//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkullar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOkullar()
        {
            this.tblAtolyeGelenZiyaretci = new HashSet<tblAtolyeGelenZiyaretci>();
            this.tblAtolyeOduncVerme = new HashSet<tblAtolyeOduncVerme>();
            this.tblAtolyeYapilanZiyaretler = new HashSet<tblAtolyeYapilanZiyaretler>();
            this.tblIlkokulSorular = new HashSet<tblIlkokulSorular>();
            this.tblLiseSorular = new HashSet<tblLiseSorular>();
            this.tblOgrenciler = new HashSet<tblOgrenciler>();
            this.tblOgretmenDYKBilgileri = new HashSet<tblOgretmenDYKBilgileri>();
            this.tblOgretmenler = new HashSet<tblOgretmenler>();
            this.tblOkulMalzemeler = new HashSet<tblOkulMalzemeler>();
            this.tblOkulOncesiSorular = new HashSet<tblOkulOncesiSorular>();
            this.tblOkulProjeEkibi = new HashSet<tblOkulProjeEkibi>();
            this.tblOkulTeknolojiTakimi = new HashSet<tblOkulTeknolojiTakimi>();
            this.tblOrtaokulSorular = new HashSet<tblOrtaokulSorular>();
        }
    
        public int OkulID { get; set; }
        public Nullable<int> OkulKodu { get; set; }
        public string OkulAdi { get; set; }
        public Nullable<int> OkulIlceAdi { get; set; }
        public Nullable<byte> OkulTuru { get; set; }
        public string OkulMuduru { get; set; }
        public Nullable<short> BTOgretmenSayisi { get; set; }
        public string OkulAdres { get; set; }
        public string OkulEposta { get; set; }
        public string OkulTel { get; set; }
        public string OkulFax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeGelenZiyaretci> tblAtolyeGelenZiyaretci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeOduncVerme> tblAtolyeOduncVerme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtolyeYapilanZiyaretler> tblAtolyeYapilanZiyaretler { get; set; }
        public virtual tblIlceler tblIlceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIlkokulSorular> tblIlkokulSorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLiseSorular> tblLiseSorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciler> tblOgrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenDYKBilgileri> tblOgretmenDYKBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgretmenler> tblOgretmenler { get; set; }
        public virtual tblOkulTuru tblOkulTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulMalzemeler> tblOkulMalzemeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulOncesiSorular> tblOkulOncesiSorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulProjeEkibi> tblOkulProjeEkibi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOkulTeknolojiTakimi> tblOkulTeknolojiTakimi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrtaokulSorular> tblOrtaokulSorular { get; set; }
    }
}
