//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkulTeknolojiTakimi
    {
        public int TakimID { get; set; }
        public Nullable<int> OkulID { get; set; }
        public string TakimAdi { get; set; }
        public Nullable<int> SorumluOgretmenID { get; set; }
        public Nullable<byte> OgrenciSayisi { get; set; }
        public string KatildigiYarismaAdi { get; set; }
    
        public virtual tblOgretmenler tblOgretmenler { get; set; }
        public virtual tblOkullar tblOkullar { get; set; }
    }
}
