//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciOgrenimBilgileri
    {
        public int OgrenciID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<byte> DersNotu { get; set; }
        public string OgretmenDersGorusu { get; set; }
        public Nullable<byte> DevamDurumu { get; set; }
    
        public virtual tblDersler tblDersler { get; set; }
        public virtual tblOgrenciler tblOgrenciler { get; set; }
    }
}
