//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodlaManisa.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOkulProjeEkibi
    {
        public int EkipID { get; set; }
        public Nullable<int> OkulID { get; set; }
        public string Yonetici { get; set; }
        public string Ogretmen1 { get; set; }
        public string Ogretmen2 { get; set; }
    
        public virtual tblOkullar tblOkullar { get; set; }
    }
}
